version: "3"
services:
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        volumes:
          - ./grafana_vol:/var/lib/grafana
        environment:
          - "GF_SECURITY_ADMIN_PASSWORD=pwd"
          # - GF_USERS_ALLOW_SIGN_UP=false
          # - GF_INSTALL_PLUGINS=grafana-piechart-panel
          - GF_SERVER_HTTP_PORT=3001
          - GF_SERVER_PROTOCOL=http
          # - GF_SERVER_DOMAIN=www.mydomain.io
          # - GF_SERVER_ROOT_URL=https://www.mydomain.io/grafana/
          - GF_SERVER_SERVE_FROM_SUB_PATH=true
        expose:
          - 3001
        networks:
          - my_network

    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 8080:80
      networks:
        - my-network-name

volumes:
   grafana_vol:

networks:
   my_network:
